### ISSUE TITLE
大佬有联系方式吗？

### ISSUE THREAD

**Issue by lyjsly** [ppambler/blog#10]
问问关于前端课程的问题~谢谢。

**Comment by ppambler** [comment]
> 问问关于前端课程的问题~谢谢。

不是大佬，你直接把问题说出来就好了

**Comment by lyjsly** [comment]
那我就直接问了吧。有没有拉勾急训的无加密课

**Comment by ppambler** [comment]
> 那我就直接问了吧。有没有拉勾急训的无加密课

没有
